/-
This file is generated by Lean Constellation.
Do not edit manually.
Node: Main.UnrestrictedOptimum
-/

import FinitePairwiseCoverageGap.Main.UnrestrictedOptimum.Defs.unrestrictedWitness
import FinitePairwiseCoverageGap.Main.UnrestrictedOptimum.Theorems.coverage_le_four
import FinitePairwiseCoverageGap.Main.UnrestrictedOptimum.Theorems.unrestricted_optimum_four
