/-
This file is generated by Lean Constellation.
Do not edit manually.
Node: Main.UnrestrictedOptimum
-/

import FinitePairwiseCoverageGap.Main.Foundations.Interfaces
import Mathlib.Algebra.BigOperators.Group.Finset.Basic
import Mathlib.Data.Finset.Card
import Mathlib.Data.Finset.Union
import Mathlib.Data.Fintype.Card
import Mathlib.Data.Fintype.Defs
import Mathlib.Data.Fintype.Powerset
import Mathlib.Data.Nat.Cast.Order.Basic
import Mathlib.Tactic.FinCases
import Mathlib.Tactic.NormNum.BigOperators
